#!/usr/bin/env bash
#configures an Nginx server to listen on port 80.

#remove the default Nginx configuration fille
rm/etc/nginx/site-enabled/default
#configure Nginx to listen on port 80 for all active IPv4 IPs
in -s/etc/nginx/sites-available/default/etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
