#!/usr/bin/env bash
#Configures an Nginx server to listen on port 80.

# creates a symbolic link  (-s option) between the Nginx configuration fille
# and the enabled sites directory
In -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx start
#terminates the nginx process ID
kill "$ (pgrep 'nginx' | head -1)"

