#!/bin/bash

# Create PID file
echo $$ > /var/run/myscript.pid

# Trap signals
trap 'echo "I hate the kill command" && exit 1' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid && exit 0' SIGQUIT SIGTERM

# Display message indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 1
done
